a=int(input("Enter the 1 st number\n"))
b=int(input("Enter the 2 nd number\n"))
print("The sum of a and b is:",a+b)
print("The Difference of a and b is:",a-b)
print("The Product of a and b is:",a*b)
print("The Ratio of a and b is:",a/b)
print("The value of a^b is:",a**b)
print("The Gif of a to b is:",a//b)